### ISSUE TITLE
 backward.hpp: 没有那个文件或目录

### ISSUE THREAD

**Issue by vell001** [gaowenliang/code_utils#6]
`code_utils-master/src/sumpixel_test.cpp:2:24: fatal error: backward.hpp: 没有那个文件或目录
compilation terminated.
`
这个sumpixel_test.hpp 里可以直接换成：
`#include "code_utils/backward.hpp"` 

实测编译通过，这样OK吗？

**Comment by anchuanxu** [comment]
可以去https://github.com/bombela/backward-cpp 下载 
将其中的backward.hpp文件copy到：`/home/YOUR_PATH/code_utils-master/src`问题解决

**Comment by johnchars** [comment]
@vell001 亲测通过 

```
#include "code_utils/sys_utils/backward.hpp"
```
为什么用上面这个不行呢，能解释一下吗？

**Comment by ChangShenXu** [comment]
> 可以去https://github.com/bombela/backward-cpp 下载
> 将其中的backward.hpp文件copy到：/home/YOUR_PATH/code_utils-master/src问题解决

亲测有效~！

**Comment by bryantaoli** [comment]
老哥,希望可以更新一下这个sumpixel_test.cpp 里可以直接换成：
#include "code_utils/backward.hpp"

**Comment by Jetson999** [comment]
edit CMakeLists.txt 

include_directories(
    include
    include/code_utils
    )

**Comment by gaowenliang** [comment]
Sorry,
I have copied the "backward.hpp" to /usr/include.
